# Generated by Django 3.2.15 on 2022-12-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID_клиента')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Номер клиента')),
                ('operator_code', models.CharField(max_length=11, verbose_name='Код оператора')),
                ('tag', models.CharField(max_length=25, verbose_name='Тег_(произвольная_метка)')),
                ('time_zone', models.DateTimeField(auto_now_add=True, verbose_name='Часвой_пояс_клиента')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID_рассылки')),
                ('DATA_START', models.DateTimeField(verbose_name='Дата_и_время_старта')),
                ('text', models.TextField(max_length=4096, verbose_name='Текст рассылки')),
                ('filter', models.CharField(max_length=256, verbose_name='Фильтр свойств клиентов')),
                ('data_time_finish', models.DateTimeField(verbose_name='Дата_и_время_окончания')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID_сообщения')),
                ('data_created', models.DateTimeField(verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Отправлено', 'SENDIN'), ('Доставлено', 'DELIVE')], max_length=12, verbose_name='Статус_отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_api.client')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_api.distribution')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('id',),
            },
        ),
    ]
