# Generated by Django 3.2.15 on 2022-12-15 21:12

from django.db import migrations, models
import django.db.models.deletion
import test_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('test_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='DATA_START',
            new_name='data_time_start',
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[test_api.validators.PhoneNumberValidator()], verbose_name='Номер клиента'),
        ),
        migrations.AlterField(
            model_name='client',
            name='time_zone',
            field=models.CharField(max_length=25, verbose_name='Часвой_пояс_клиента'),
        ),
        migrations.AlterField(
            model_name='message',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='test_api.client'),
        ),
        migrations.AlterField(
            model_name='message',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='test_api.distribution'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус_отправки'),
        ),
    ]
